namespace WoWChat.Net.Realm;

public enum RealmAuthCommand : byte
{
  CMD_AUTH_LOGON_CHALLENGE = 0x00,
  CMD_AUTH_LOGON_PROOF = 0x01,
  CMD_REALM_LIST = 0x10,
  CMD_REALM_TRANSFER_INITIATE = 0x30,
  CMD_REALM_TRANSFER_DATA = 0x31,
  CMD_REALM_TRANSFER_ACCEPT = 0x32,
  CMD_REALM_TRANSFER_RESUME = 0x33,
  CMD_REALM_TRANSFER_CANCEL = 0x34
}
