name: WoWChat.Net PR

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - 'master/**'
    paths:
      - 'WoWChat.Net/**'
      - '!WoWChat.Net/README.md'
      - '!WoWChat.Net/docs/**'
      - 'WoWChat.Net.Tests/**'
      - '!WoWChat.Net.Tests/README.md'
      - '!WoWChat.Net.Tests/docs/**'

jobs:
  validate:

    runs-on: ubuntu-latest
    env:
      working-directory: ./WoWChat.Net
      cache-key: ./WoWChat.Net-pr
    
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        dotnet-version: ['6.x']

    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      -
        name: Run dotnet format
        run: dotnet format --verify-no-changes
      - 
        name: Install dependencies
        run: dotnet restore
      -
        name: Test
        run: dotnet test --no-restore --verbosity normal