name: WoWChat.Net CD

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths:
      - 'WoWChat.Net/**'
      - '!WoWChat.Net/README.md'
      - '!WoWChat.Net/docs/**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
      DOTNET_CLI_TELEMETRY_OPTOUT: "true"
      working-directory: ./WoWChat.Net
      cache-key: WoWChat.Net-cd
    
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.working-directory }}

    strategy:
      matrix:
        dotnet-version: ['6.x']

    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - 
        name: Install dependencies
        run: dotnet restore
      - 
        name: Build
        run: dotnet publish --configuration Release --no-restore
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: WoWChat.Net Assembly
          path: ${{ github.workspace }}/WoWChat.Net/bin/Release/net6.0/publish/
      -
        name: Pack solution and generate NuGet package
        run: dotnet pack --configuration Release --no-restore -o out  
      -
        name: Authenticate to Github Packages
        run: dotnet nuget add source --username ${{ secrets.NUGET_GITHUB_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/beholder-rpa/index.json"
      -
        name: Install gpr
        run: dotnet tool install gpr --global
      -
        name: gpr upload
        run: find -name "*.nupkg" -print -exec gpr push -k ${{secrets.GITHUB_TOKEN}} {} \;
